<a href="https://colab.research.google.com/github/F-Neres/Python_Notes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>

In [5]:
#   Versão do Numpy

np.__version__

'1.21.5'

#### Atualizar o numpy, no prompt:

pip install numpy -U

In [6]:
!pip install numpy -U

## Criação de Array

In [ ]:
# O que há num array

help(np.array)

In [35]:
# Criação de array com lista

Lista = [1,2,3,4,5,6,7,8,9,10.] #Colocar um ponto num número determina que o tipo seja "float"
Vetor = np.array(Lista)

#Um vetor é um array com apenas uma dimensão.
#Cada dimensão é uma camada (isso será visto mais a diante).
# Um array com uma camada tem uma lista.

print(Vetor)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [38]:
# Criação de Array com Arange
# Os parâmetros são: início, fim e intervalo (a distância entre cada número)

VetorArange = np.arange(1,1) #Este array começa e termina no mesmo número, o que faz o array ficar vazio
print(VetorArange)

VetorArange = np.arange(10,1) #Ele tenta somar um como "passo", mas não consegue chegar a um número menor somando, então encerra sem adicionar número algum
print(VetorArange)

VetorArange = np.arange(10,1,-1) # Dando o "passo" negativo, somando o valor do passo ao valor inicial, é possível chegar ao valor final.
print(VetorArange)

VetorArange = np.arange(10,1,-1.,dtype='int64') #É possível determinar o tipo; caso contrário, ele é inferido pelos números dados
# Mesmo dado um número com um ponto, o dtype foi estipulado com sucesso

[]
[]
[10  9  8  7  6  5  4  3  2]


In [48]:
# Um array preenchido com zeros
# O primeiro parâmetro é o shape do array - dado em uma tupla

VetorZeros = np.zeros((5,20)) # Uma matriz de 5x20 (5 vetores de 20 itens)
print(VetorZeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Investigação dos Arrays

In [39]:
# O tipo é ndarray - numpy data array
print(type(Vetor))

<class 'numpy.ndarray'>


In [40]:
# Guia-se por índices
# A atribuição de valores é similar à de uma lista:

Vetor[0] = 8
print(Vetor)
print(Vetor[9])

[ 8.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
10.0


In [41]:
# O formato do array:

print(Vetor.shape)
print(type(Vetor.shape))

#O resultado é uma tupla, onde cada número é a quantidade de vetores em cada dimensão

(10,)
<class 'tuple'>


In [42]:
#dtype é o tipo dos dados
#Arrays só aceitam dados de um mesmo tipo, e apenas números

print(Vetor.dtype,)
print(VetorArange.dtype,)

print('')

print(type(Vetor.dtype))


float64
int64

<class 'numpy.dtype[float64]'>


## Métodos do Array

In [43]:
#Soma acumulada.

VetorCumSum = Vetor.cumsum()
print(VetorCumSum)
print(type(VetorCumSum))

# O resultado é outro array

[ 8. 10. 13. 17. 22. 28. 35. 43. 52. 62.]
<class 'numpy.ndarray'>
