In [2]:
import numpy as np

In [3]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>

In [4]:
#   Versão do Numpy

np.__version__

'1.21.5'

#### Atualizar o numpy, no prompt:

pip install numpy -U

In [5]:
!pip install numpy -U

In [6]:
# O que há num array

help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

## Criação de Array

In [58]:
# Criação de array com lista

Lista = [1,2,3,4,5,6,7,8,9,10.] #Colocar um ponto num número determina que o tipo seja "float"
Vetor = np.array(Lista)

#Um vetor é um array com apenas uma dimensão.
#Cada dimensão é uma camada (isso será visto mais a diante).
# Um array com uma camada tem uma lista.

print(Vetor)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [65]:
#Criando uma lista composta por listas.

Lista_Lista = [Lista for i in range(len(Lista)-2)]
print(Lista_Lista)

print()

# Isso proporcionará criar um array bidimensional, uma matriz:
Matriz = np.array(Lista_Lista)
print(Matriz)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10.0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10.0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10.0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10.0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10.0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10.0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10.0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10.0]]

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


In [8]:
# Criação de Array com Arange
# Os parâmetros são: início, fim e intervalo (a distância entre cada número)

VetorArange = np.arange(1,1) #Este array começa e termina no mesmo número, o que faz o array ficar vazio
print(VetorArange)

VetorArange = np.arange(10,1) #Ele tenta somar um como "passo", mas não consegue chegar a um número menor somando, então encerra sem adicionar número algum
print(VetorArange)

VetorArange = np.arange(10,1,-1) # Dando o "passo" negativo, somando o valor do passo ao valor inicial, é possível chegar ao valor final.
print(VetorArange)

VetorArange = np.arange(10,1,-1.,dtype='int64') #É possível determinar o tipo; caso contrário, ele é inferido pelos números dados
# Mesmo dado um número com um ponto, o dtype foi estipulado com sucesso

[]
[]
[10  9  8  7  6  5  4  3  2]


In [9]:
# Um array preenchido com zeros
# O primeiro parâmetro é o shape do array - dado em uma tupla

MatrizZeros = np.zeros((5,20)) # Uma matriz de 5x20 (5 vetores de 20 itens)
print(MatrizZeros)

print()

MatrizZerosLike = np.zeros_like(VetorArange) #Cria um array com o mesmo shape de outro, mas com todos os valores sendo zero
print(MatrizZerosLike)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[0 0 0 0 0 0 0 0 0]


In [24]:
# Retorna uma matriz (um array bidimensional) com todos os valores zero, exceto numa diagonal

MatrizOlho = np.eye(5)
print(MatrizOlho)

#Deslocando a diagonal para baixo e determiando o número de colunas (valores dentro dos vetores)
print()

MatrizOlho2 = np.eye(N=15,M=7,k=-4)
print(MatrizOlho2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [16]:
# Como o "eye", mas a lista serve como valores das diagonais
# Forma uma matriz com lados do tamanho da lista.

MatrizDiag = np.diag(Lista)

print(MatrizDiag)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  6.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  8.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]]


In [53]:
# Cria um vetor com N valores (defaut = 50) que vai de primeiro parâmetro ao segundo

VetorLinspace = np.linspace(0,50)
print(VetorLinspace)
print()
VetorLinspace = np.linspace(0,10)
print(VetorLinspace)

print()

VetorLinspace = np.linspace(start=0,stop=10,num=2,endpoint=False,axis=-1)
#Dois valores(num), não incluindo o último (endpoind),
print(VetorLinspace)

[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061 

In [56]:
#Como o linspace, mas os valores são dados em log.

VetorLogspace = np.logspace(10,50,40)
print(VetorLogspace)

print()

VetorLogspace = np.logspace(0,1,40)
print(VetorLogspace)

[1.00000000e+10 1.06081836e+11 1.12533558e+12 1.19377664e+13
 1.26638017e+14 1.34339933e+15 1.42510267e+16 1.51177507e+17
 1.60371874e+18 1.70125428e+19 1.80472177e+20 1.91448198e+21
 2.03091762e+22 2.15443469e+23 2.28546386e+24 2.42446202e+25
 2.57191381e+26 2.72833338e+27 2.89426612e+28 3.07029063e+29
 3.25702066e+30 3.45510729e+31 3.66524124e+32 3.88815518e+33
 4.12462638e+34 4.37547938e+35 4.64158883e+36 4.92388263e+37
 5.22334507e+38 5.54102033e+39 5.87801607e+40 6.23550734e+41
 6.61474064e+42 7.01703829e+43 7.44380301e+44 7.89652287e+45
 8.37677640e+46 8.88623816e+47 9.42668455e+48 1.00000000e+50]

[ 1.          1.06081836  1.12533558  1.19377664  1.26638017  1.34339933
  1.42510267  1.51177507  1.60371874  1.70125428  1.80472177  1.91448198
  2.03091762  2.15443469  2.28546386  2.42446202  2.57191381  2.72833338
  2.89426612  3.07029063  3.25702066  3.45510729  3.66524124  3.88815518
  4.12462638  4.37547938  4.64158883  4.92388263  5.22334507  5.54102033
  5.87801607  6.2355073

## Investigação dos Arrays

In [11]:
# O tipo é ndarray - numpy data array
print(type(Vetor))

<class 'numpy.ndarray'>


In [12]:
# Guia-se por índices
# A atribuição de valores é similar à de uma lista:

Vetor[0] = 8
print(Vetor)
print(Vetor[9])

[ 8.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
10.0


In [66]:
# O formato do array:

print(Vetor.shape)
print(type(Vetor.shape))

print()
print(Matriz.shape)

#O resultado é uma tupla, onde cada número é o tamanho de cada dimensão
#Em comparação com as listas matrioskas, o continente vem antes do conteúdo.

(10,)
<class 'tuple'>

(8, 10)


In [14]:
#dtype é o tipo dos dados
#Arrays só aceitam dados de um mesmo tipo, e apenas números

print(Vetor.dtype,)
print(VetorArange.dtype,)

print('')

print(type(Vetor.dtype))


float64
int64

<class 'numpy.dtype[float64]'>


In [35]:
#Fornece os índices da diagonal de um array


DiagIndices = np.diag_indices(3,4)
# A diagonal de uma matriz hipotética com N atributos e M dimensões, sendo np.diag_indices(N,M)

print(1,DiagIndices)
print(2,type(DiagIndices))
for i in DiagIndices:
  print()
  print(3,i)
  print(4,type(i))

try:
  DiagIndices2 = np.diag_indices_from(VetorOlho2)
  # Os índices de uma diagonal dada
except ValueError:
  print(5,ValueError.with_traceback)
  # Todas as dimensões do array precisam ter o mesmo tamanho para que haja uma diagonal definida
else:
  print(6,DiagIndices2)





1 (array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]))
2 <class 'tuple'>

3 [0 1 2]
4 <class 'numpy.ndarray'>

3 [0 1 2]
4 <class 'numpy.ndarray'>

3 [0 1 2]
4 <class 'numpy.ndarray'>

3 [0 1 2]
4 <class 'numpy.ndarray'>
<method 'with_traceback' of 'BaseException' objects>


## Métodos do Array

In [15]:
#Soma acumulada.

VetorCumSum = Vetor.cumsum()
print(VetorCumSum)
print(type(VetorCumSum))

# O resultado é outro array

[ 8. 10. 13. 17. 22. 28. 35. 43. 52. 62.]
<class 'numpy.ndarray'>
