<a href="https://colab.research.google.com/github/F-Neres/Python_Notes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>

In [5]:
#   Versão do Numpy

np.__version__

'1.21.5'

#### Atualizar o numpy, no prompt:

pip install numpy -U

In [6]:
!pip install numpy -U

## Array

In [ ]:
# O que há num array

help(np.array)

In [12]:
Lista = [1,2,3,4,5,6,7,8,9,10]
Vetor = np.array(Lista)

#Um vetor é um array com apenas uma dimensão.
#Cada dimensão é uma camada (isso será visto mais a diante).
# Um array com uma camada tem uma lista.

print(Vetor)
print(type(Vetor)) #tipo: ndarray (numpy data array)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [19]:
# Guia-se por índices
# A atribuição de valores é similar à de uma lista:

Vetor[0] = 8
print(Vetor)
print(Vetor[9])

[ 8  2  3  4  5  6  7  8  9 10]
10


## Métodos do Array

In [15]:
#Soma acumulada.

VetorCumSum = Vetor.cumsum()
print(VetorCumSum)
print(type(VetorCumSum))

# O resultado é outro array

[ 1  3  6 10 15 21 28 36 45 55]
<class 'numpy.ndarray'>
