In [2]:
import numpy as np

In [3]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>

In [4]:
#   Versão do Numpy

np.__version__

'1.21.5'

#### Atualizar o numpy, no prompt:

pip install numpy -U

In [5]:
!pip install numpy -U

## Criação de Array

In [6]:
# O que há num array

help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [7]:
# Criação de array com lista

Lista = [1,2,3,4,5,6,7,8,9,10.] #Colocar um ponto num número determina que o tipo seja "float"
Vetor = np.array(Lista)

#Um vetor é um array com apenas uma dimensão.
#Cada dimensão é uma camada (isso será visto mais a diante).
# Um array com uma camada tem uma lista.

print(Vetor)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
# Criação de Array com Arange
# Os parâmetros são: início, fim e intervalo (a distância entre cada número)

VetorArange = np.arange(1,1) #Este array começa e termina no mesmo número, o que faz o array ficar vazio
print(VetorArange)

VetorArange = np.arange(10,1) #Ele tenta somar um como "passo", mas não consegue chegar a um número menor somando, então encerra sem adicionar número algum
print(VetorArange)

VetorArange = np.arange(10,1,-1) # Dando o "passo" negativo, somando o valor do passo ao valor inicial, é possível chegar ao valor final.
print(VetorArange)

VetorArange = np.arange(10,1,-1.,dtype='int64') #É possível determinar o tipo; caso contrário, ele é inferido pelos números dados
# Mesmo dado um número com um ponto, o dtype foi estipulado com sucesso

[]
[]
[10  9  8  7  6  5  4  3  2]


In [9]:
# Um array preenchido com zeros
# O primeiro parâmetro é o shape do array - dado em uma tupla

MatrizZeros = np.zeros((5,20)) # Uma matriz de 5x20 (5 vetores de 20 itens)
print(MatrizZeros)

print()

MatrizZerosLike = np.zeros_like(VetorArange) #Cria um array com o mesmo shape de outro, mas com todos os valores sendo zero
print(MatrizZerosLike)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[0 0 0 0 0 0 0 0 0]


In [24]:
# Retorna uma matriz (um array bidimensional) com todos os valores zero, exceto numa diagonal

MatrizOlho = np.eye(5)
print(MatrizOlho)

#Deslocando a diagonal para baixo e determiando o número de colunas (valores dentro dos vetores)
print()

MatrizOlho2 = np.eye(N=15,M=7,k=-4)
print(MatrizOlho2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [16]:
# Como o "eye", mas a lista serve como valores das diagonais
# Forma uma matriz com lados do tamanho da lista.

MatrizDiag = np.diag(Lista)

print(MatrizDiag)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  6.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  8.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]]


In [ ]:
VetorLinspace

## Investigação dos Arrays

In [11]:
# O tipo é ndarray - numpy data array
print(type(Vetor))

<class 'numpy.ndarray'>


In [12]:
# Guia-se por índices
# A atribuição de valores é similar à de uma lista:

Vetor[0] = 8
print(Vetor)
print(Vetor[9])

[ 8.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
10.0


In [13]:
# O formato do array:

print(Vetor.shape)
print(type(Vetor.shape))

#O resultado é uma tupla, onde cada número é a quantidade de vetores em cada dimensão

(10,)
<class 'tuple'>


In [14]:
#dtype é o tipo dos dados
#Arrays só aceitam dados de um mesmo tipo, e apenas números

print(Vetor.dtype,)
print(VetorArange.dtype,)

print('')

print(type(Vetor.dtype))


float64
int64

<class 'numpy.dtype[float64]'>


In [35]:
#Fornece os índices da diagonal de um array


DiagIndices = np.diag_indices(3,4)
# A diagonal de uma matriz hipotética com N atributos e M dimensões, sendo np.diag_indices(N,M)

print(1,DiagIndices)
print(2,type(DiagIndices))
for i in DiagIndices:
  print()
  print(3,i)
  print(4,type(i))

try:
  DiagIndices2 = np.diag_indices_from(VetorOlho2)
  # Os índices de uma diagonal dada
except ValueError:
  print(5,ValueError.with_traceback)
  # Todas as dimensões do array precisam ter o mesmo tamanho para que haja uma diagonal definida
else:
  print(6,DiagIndices2)





1 (array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]))
2 <class 'tuple'>

3 [0 1 2]
4 <class 'numpy.ndarray'>

3 [0 1 2]
4 <class 'numpy.ndarray'>

3 [0 1 2]
4 <class 'numpy.ndarray'>

3 [0 1 2]
4 <class 'numpy.ndarray'>
<method 'with_traceback' of 'BaseException' objects>


## Métodos do Array

In [15]:
#Soma acumulada.

VetorCumSum = Vetor.cumsum()
print(VetorCumSum)
print(type(VetorCumSum))

# O resultado é outro array

[ 8. 10. 13. 17. 22. 28. 35. 43. 52. 62.]
<class 'numpy.ndarray'>
